name: Monthly Article Processor

on:
  schedule:
    - cron: '00 19 1 * *'  # 7:00 PM UTC on the 1st
  workflow_dispatch:

jobs:
  process-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install spacy
          python -m spacy download en_core_web_sm
          pip install -r requirements.txt
          python -c "import spacy; spacy.load('en_core_web_sm')"  # Verify spaCy installation

      - name: Clear Python Cache
        run: |
          find . -type d -name "__pycache__" -exec rm -r {} +

      - name: Run Article Processor
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: brand_monitoring
          RAW_COLLECTION: raw_articles
          PROCESSED_COLLECTION: processed_articles
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
        run: python data_processor.py
